name: Generate Allure Test Report

on:
  workflow_run:
    workflows: ["Unit Tests (CI)"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'completed'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: allure-results-autoupdater
        path: ./allure-results
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        
    - name: Setup Allure
      uses: simple-elf/allure-report-action@v1.9
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: allure-history
        allure_history: allure-history
        keep_reports: 20
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./allure-history
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4