name: Unit Tests (CI)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.SUBMODULE_TOKEN || github.token }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Create Allure results directory
      run: mkdir -p ./allure-results
        
    - name: Run Unit Tests Only
      run: |
        # Build and test only unit tests, avoiding solution file issues and generate Allure results
        dotnet test tests/ModelingEvolution.AutoUpdater.Tests/ \
          --configuration Release \
          --logger "console;verbosity=normal"
        
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-autoupdater
        path: ./allure-results
        retention-days: 30